language: node_js
cache:
  directories:
    - node_modules
script:
  - yarn lint
  - yarn test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
