language: node_js
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn lint
  - yarn test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: build
  on:
    branch: master
